version: 2
jobs:
  build:
    docker:
      - image: nimlang/nim
    resource_class: small
    steps:
      - run: echo 'export PATH=~/.nimble/bin:$PATH' >> $BASH_ENV
      - checkout
      # Reuse cached directories
      - restore_cache:
          key: nim-0000
      - save_cache:
          key: nim-0000
          paths:
            - .nimble
      - run: mkdir test_results
      - run: nimble test -y
      - store_test_results:
          path: test_results/
