name: Run Test Suites

on:
  pull_request:
    branches:
    - main
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: ouzi-dev/commit-status-updater@v1.1.0
    - name: Cache choosenim
      id: cache-choosenim
      uses: actions/cache@v1
      with:
        path: ~/.choosenim
        key: ${{ runner.os }}-choosenim-devel-latest
        
    - name: Setup Nim Enviroment
      uses: actions/checkout@master
    - uses: jiro4989/setup-nim-action@v1
      with:
        nim-version: 'stable'
      
    - name: Run Tests
      env: # Or as an environment variable
        AZURE_SECRET_KEY: ${{ secrets.AZURE_SECRET_KEY }}
      run: nimble update && nimble test
    - if: always()
      uses: ouzi-dev/commit-status-updater@v1.1.0
      with:
        status: "${{ job.status }}"
